// Generated by scripts/render-login-art from theme/login-layout.json.
var promptWidth = 451;
var promptHeight = 325;
var fieldWidth = 381;
var fieldHeight = 54;
var fieldY = 138;
var buttonY = 208;
var buttonHeight = 48;
var hintY = 268;
var logoWidth = 840;
var logoGap = 8;
var baseScale = 0.75;
var referenceWidth = 1920;
var referenceHeight = 1080;
