// Generated by scripts/render-palette from theme/colors.toml.
var background = "#0c1015"
var dark = "#07090e"
var burgundy = "#33121d"
var panel = "#0c1015"
var red = "#ff3045"
var cyan = "#53e3d2"
var text = "#e5f1ee"
var dim = "#868c93"
